### ISSUE TITLE
Review package

### ISSUE THREAD

**Issue by sskorik01** [openwashdata/cleanteamghana#3]
Hi @larnsce,

Could you review and give me feedback on this package, so that I can finalize it? Thank you!

**Comment by larnsce** [comment]
Well done, you are becoming very efficient at putting these packages together. Did you every hear back from the authors?

Comments to resolve:

- Please add a visualising at the beginning of the README. You can use one of the visualisations that you have at the bottom.
- (low priority): The text for the citation information at the end is in German. I believe it's your system language, check if there is a locale you could use to make that English.
- Please include an actual reference and citation for the paper under heading "The research paper":

The research paper associated with this data package is named “Evaluation of user experiences for the Clean Team Ghana container-based sanitation service in Kumasi, Ghana” 
(Tidwell et al., 2022).

Tidwell, J. B., Nyarko, K. B., Ross, I., Dwumfour-Asare, B., & Scott, P. (2022). Evaluation of user experiences for the Clean Team Ghana container-based sanitation service in Kumasi, Ghana. Journal of Water, Sanitation and Hygiene for Development, 12(3), 336–346. https://doi.org/10.2166/washdev.2022.013

**Comment by larnsce** [comment]
Thanks, that sounds good. Send them a follow-up with the final data package.

**Comment by sskorik01** [comment]
Ok, will do!
